module.exports = [{
  name: 'Jaskolski-Daniel',
  type: 'Electrical',
  description: 'tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis',
  contacts: {
    contactPerson: 'Hadlee Sallan',
    available: '0 - 24 h',
    tel: '542-704-2692',
    email: 'hsallan0@wordpress.org',
    addr: {
      city: 'Berendeyevo',
      street: 'Badeau',
      houseNumber: '2',
    },
    webpageUrl: 'https://reddit.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000000',
}, {
  name: 'Predovic-Quigley',
  type: 'Overhead Doors',
  description: 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl',
  contacts: {
    contactPerson: 'Tybalt Sandilands',
    available: '0 - 24 h',
    tel: '246-759-0421',
    email: 'tsandilands1@bloomberg.com',
    addr: {
      city: 'Jiachuan',
      street: 'Scofield',
      houseNumber: '6807',
    },
    webpageUrl: 'https://nba.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000001',
}, {
  name: 'Hane and Sons',
  type: 'Wall Protection',
  description: 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed',
  contacts: {
    contactPerson: 'Lucine Croutear',
    available: '0 - 24 h',
    tel: '373-252-3541',
    email: 'lcroutear2@upenn.edu',
    addr: {
      city: 'Kultuk',
      street: 'Heffernan',
      houseNumber: '012',
    },
    webpageUrl: 'https://stumbleupon.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000002',
}, {
  name: 'Wolff-Lubowitz',
  type: 'Elevator',
  description: 'vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat',
  contacts: {
    contactPerson: 'Dione Mathey',
    available: 'H-P: 8:00 - 16:00',
    tel: '155-591-0341',
    email: 'dmathey3@friendfeed.com',
    addr: {
      city: "Na'ale",
      street: 'Menomonie',
      houseNumber: '17',
    },
    webpageUrl: 'https://google.ca',
  },
  active: true,
  uploader: '61182751fc13ae78fd000003',
}, {
  name: 'Johnston Inc',
  type: 'Casework',
  description: 'erat vestibulum sed magna at nunc commodo placerat praesent blandit',
  contacts: {
    contactPerson: 'Hanna Fenwick',
    available: 'H-P: 8:00 - 16:00',
    tel: '720-941-9103',
    email: 'hfenwick4@jimdo.com',
    addr: {
      city: 'Princeville',
      street: 'Morningstar',
      houseNumber: '18528',
    },
    webpageUrl: 'http://illinois.edu',
  },
  active: true,
  uploader: '61182751fc13ae78fd000004',
}, {
  name: 'Gerlach Inc',
  type: 'Framing (Steel)',
  description: 'dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris',
  contacts: {
    contactPerson: 'Anne-corinne Tiery',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '977-809-3570',
    email: 'atiery5@hugedomains.com',
    addr: {
      city: 'Hekou',
      street: 'Elgar',
      houseNumber: '7',
    },
    webpageUrl: 'http://printfriendly.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000005',
}, {
  name: 'Heathcote and Sons',
  type: 'Curb & Gutter',
  description: 'ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet',
  contacts: {
    contactPerson: 'Ninnetta Pietruschka',
    available: '0 - 24 h',
    tel: '243-999-4259',
    email: 'npietruschka6@over-blog.com',
    addr: {
      city: '‘Ibwayn',
      street: 'Ridge Oak',
      houseNumber: '11998',
    },
    webpageUrl: 'http://nsw.gov.au',
  },
  active: false,
  uploader: '61182751fc13ae78fd000006',
}, {
  name: 'Schulist and Sons',
  type: 'Framing (Steel)',
  description: 'eleifend quam a odio in hac habitasse platea dictumst maecenas',
  contacts: {
    contactPerson: 'Eddy Andre',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '461-521-4221',
    email: 'eandre7@sogou.com',
    addr: {
      city: 'Yushan',
      street: 'Dottie',
      houseNumber: '39223',
    },
    webpageUrl: 'http://comsenz.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000007',
}, {
  name: "Stark-D'Amore",
  type: 'Asphalt Paving',
  description: 'at feugiat non pretium quis lectus suspendisse potenti in eleifend',
  contacts: {
    contactPerson: 'Felicdad Spikings',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '452-909-1036',
    email: 'fspikings8@people.com.cn',
    addr: {
      city: 'Candelaria',
      street: 'Pankratz',
      houseNumber: '40',
    },
    webpageUrl: 'http://wikimedia.org',
  },
  active: false,
  uploader: '61182751fc13ae78fd000008',
}, {
  name: 'Carroll-Shields',
  type: 'Site Furnishings',
  description: 'pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa',
  contacts: {
    contactPerson: 'Wake Eveque',
    available: '0 - 24 h',
    tel: '831-929-2088',
    email: 'weveque9@bluehost.com',
    addr: {
      city: 'İsmayıllı',
      street: 'Milwaukee',
      houseNumber: '1608',
    },
    webpageUrl: 'http://narod.ru',
  },
  active: true,
  uploader: '61182751fc13ae78fd000009',
}, {
  name: 'Volkman Inc',
  type: 'Painting & Vinyl Wall Covering',
  description: 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio',
  contacts: {
    contactPerson: "Slade O'Malley",
    available: '0 - 24 h',
    tel: '568-552-4802',
    email: 'somalleya@foxnews.com',
    addr: {
      city: 'Sambongmulyo',
      street: 'Superior',
      houseNumber: '3',
    },
    webpageUrl: 'http://phpbb.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00000a',
}, {
  name: 'Bernhard, Romaguera and Bernier',
  type: 'Ornamental Railings',
  description: 'id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed',
  contacts: {
    contactPerson: 'Harley Ferrino',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '738-906-5278',
    email: 'hferrinob@google.de',
    addr: {
      city: 'Žiželice',
      street: 'Morning',
      houseNumber: '2378',
    },
    webpageUrl: 'https://tumblr.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd00000b',
}, {
  name: 'Kris-Lowe',
  type: 'Casework',
  description: 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo',
  contacts: {
    contactPerson: 'Melodee Eloy',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '129-913-7118',
    email: 'meloyc@wufoo.com',
    addr: {
      city: 'Parungjawa',
      street: 'Sunfield',
      houseNumber: '1',
    },
    webpageUrl: 'http://woothemes.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd00000c',
}, {
  name: 'Lebsack-Ullrich',
  type: 'Hard Tile & Stone',
  description: 'justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales',
  contacts: {
    contactPerson: 'Alida Berriman',
    available: '0 - 24 h',
    tel: '893-613-5748',
    email: 'aberrimand@angelfire.com',
    addr: {
      city: 'Qingxi',
      street: 'Sommers',
      houseNumber: '54651',
    },
    webpageUrl: 'https://icio.us',
  },
  active: true,
  uploader: '61182751fc13ae78fd00000d',
}, {
  name: 'Grady-Braun',
  type: 'Curb & Gutter',
  description: 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at',
  contacts: {
    contactPerson: 'Annadiane Standfield',
    available: '0 - 24 h',
    tel: '961-253-7312',
    email: 'astandfielde@state.gov',
    addr: {
      city: 'Puzi',
      street: 'Kim',
      houseNumber: '501',
    },
    webpageUrl: 'https://sogou.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00000e',
}, {
  name: 'Abbott-Champlin',
  type: 'Electrical',
  description: 'adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere',
  contacts: {
    contactPerson: 'Rickie Juan',
    available: 'H-P: 8:00 - 16:00',
    tel: '127-335-2731',
    email: 'rjuanf@alibaba.com',
    addr: {
      city: 'Ndewel',
      street: 'Elka',
      houseNumber: '914',
    },
    webpageUrl: 'https://soundcloud.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00000f',
}, {
  name: 'King-Gerhold',
  type: 'Masonry',
  description: 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut',
  contacts: {
    contactPerson: 'Milt Copcott',
    available: '0 - 24 h',
    tel: '769-828-9740',
    email: 'mcopcottg@columbia.edu',
    addr: {
      city: 'Grybów',
      street: 'Anderson',
      houseNumber: '7',
    },
    webpageUrl: 'http://gizmodo.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000010',
}, {
  name: 'Heller Group',
  type: 'Waterproofing & Caulking',
  description: 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod',
  contacts: {
    contactPerson: 'Horatia Clifford',
    available: '0 - 24 h',
    tel: '406-573-5161',
    email: 'hcliffordh@google.ca',
    addr: {
      city: 'Bagratashen',
      street: 'Graceland',
      houseNumber: '98',
    },
    webpageUrl: 'http://yolasite.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000011',
}, {
  name: 'Larson, Langworth and Hickle',
  type: 'Temp Fencing, Decorative Fencing and Gates',
  description: 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris',
  contacts: {
    contactPerson: 'Bendix Dugan',
    available: 'H-P: 8:00 - 16:00',
    tel: '644-761-7429',
    email: 'bdugani@engadget.com',
    addr: {
      city: 'Mniszków',
      street: 'Hudson',
      houseNumber: '2030',
    },
    webpageUrl: 'https://acquirethisname.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000012',
}, {
  name: 'Von LLC',
  type: 'Termite Control',
  description: 'luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur',
  contacts: {
    contactPerson: 'Dirk Kniveton',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '440-201-4447',
    email: 'dknivetonj@google.com.br',
    addr: {
      city: 'Cikupa',
      street: 'Memorial',
      houseNumber: '403',
    },
    webpageUrl: 'https://ning.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000013',
}, {
  name: 'Barton, Towne and McDermott',
  type: 'Curb & Gutter',
  description: 'molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget',
  contacts: {
    contactPerson: 'Noell Capaldo',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '156-736-4895',
    email: 'ncapaldok@usnews.com',
    addr: {
      city: 'Saint-Lin-Laurentides',
      street: 'Morning',
      houseNumber: '9408',
    },
    webpageUrl: 'http://canalblog.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000014',
}, {
  name: 'Harber, Fisher and Gutmann',
  type: 'Granite Surfaces',
  description: 'nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id',
  contacts: {
    contactPerson: 'Isidora Vick',
    available: 'H-P: 8:00 - 16:00',
    tel: '743-381-6748',
    email: 'ivickl@nyu.edu',
    addr: {
      city: 'Francistown',
      street: 'Mcbride',
      houseNumber: '9',
    },
    webpageUrl: 'https://lycos.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000015',
}, {
  name: 'Gerlach-Bode',
  type: 'Drywall & Acoustical (MOB)',
  description: 'nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus',
  contacts: {
    contactPerson: 'Sid Cowton',
    available: '0 - 24 h',
    tel: '791-863-1785',
    email: 'scowtonm@jalbum.net',
    addr: {
      city: 'Monte de Trigo',
      street: 'Linden',
      houseNumber: '29457',
    },
    webpageUrl: 'http://cisco.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000016',
}, {
  name: 'Bins, Zemlak and Leannon',
  type: 'Electrical and Fire Alarm',
  description: 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt',
  contacts: {
    contactPerson: 'Chico Harmer',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '344-565-9562',
    email: 'charmern@theglobeandmail.com',
    addr: {
      city: 'Qingjiang',
      street: 'Green',
      houseNumber: '0',
    },
    webpageUrl: 'http://ft.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000017',
}, {
  name: 'Bernhard-Schmeler',
  type: 'Hard Tile & Stone',
  description: 'donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla',
  contacts: {
    contactPerson: 'Portie Helder',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '422-292-4221',
    email: 'pheldero@biglobe.ne.jp',
    addr: {
      city: 'Pu’er',
      street: 'Tennessee',
      houseNumber: '0413',
    },
    webpageUrl: 'http://japanpost.jp',
  },
  active: true,
  uploader: '61182751fc13ae78fd000018',
}, {
  name: 'Schneider, Yundt and Treutel',
  type: 'Masonry',
  description: 'tortor duis mattis egestas metus aenean fermentum donec ut mauris eget',
  contacts: {
    contactPerson: 'Garrett McKintosh',
    available: 'H-P: 8:00 - 16:00',
    tel: '981-505-9943',
    email: 'gmckintoshp@ftc.gov',
    addr: {
      city: 'Magangué',
      street: 'Warrior',
      houseNumber: '4327',
    },
    webpageUrl: 'http://cnn.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000019',
}, {
  name: 'Hettinger-Donnelly',
  type: 'Casework',
  description: 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur',
  contacts: {
    contactPerson: 'Leandra Sterzaker',
    available: '0 - 24 h',
    tel: '378-297-2531',
    email: 'lsterzakerq@bbb.org',
    addr: {
      city: 'Nueva Vida Sur',
      street: 'Nobel',
      houseNumber: '124',
    },
    webpageUrl: 'http://youtu.be',
  },
  active: false,
  uploader: '61182751fc13ae78fd00001a',
}, {
  name: 'Gutkowski, VonRueden and Davis',
  type: 'Masonry',
  description: 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing',
  contacts: {
    contactPerson: 'Dorthea Nicholas',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '408-688-0623',
    email: 'dnicholasr@washingtonpost.com',
    addr: {
      city: 'San Jose',
      street: 'Mcbride',
      houseNumber: '20559',
    },
    webpageUrl: 'https://hubpages.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00001b',
}, {
  name: 'Schmidt, Yundt and Kemmer',
  type: 'Structural and Misc Steel (Fabrication)',
  description: 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia',
  contacts: {
    contactPerson: 'Gregorius Raimbauld',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '899-262-5514',
    email: 'graimbaulds@chron.com',
    addr: {
      city: 'Shigongqiao',
      street: 'Weeping Birch',
      houseNumber: '74',
    },
    webpageUrl: 'https://dmoz.org',
  },
  active: true,
  uploader: '61182751fc13ae78fd00001c',
}, {
  name: "D'Amore-Walsh",
  type: 'Granite Surfaces',
  description: 'pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus',
  contacts: {
    contactPerson: 'Cazzie Rillatt',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '636-262-5369',
    email: 'crillattt@weibo.com',
    addr: {
      city: 'Dmitriyevka',
      street: 'Dahle',
      houseNumber: '86469',
    },
    webpageUrl: 'http://dailymail.co.uk',
  },
  active: false,
  uploader: '61182751fc13ae78fd00001d',
}, {
  name: 'Douglas, Gibson and Kerluke',
  type: 'Painting & Vinyl Wall Covering',
  description: 'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum',
  contacts: {
    contactPerson: 'Margarete Railton',
    available: '0 - 24 h',
    tel: '109-338-8227',
    email: 'mrailtonu@timesonline.co.uk',
    addr: {
      city: 'Herrljunga',
      street: 'Maple',
      houseNumber: '4299',
    },
    webpageUrl: 'http://discuz.net',
  },
  active: false,
  uploader: '61182751fc13ae78fd00001e',
}, {
  name: 'Anderson Inc',
  type: 'Doors, Frames & Hardware',
  description: 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim',
  contacts: {
    contactPerson: 'Yance Izachik',
    available: '0 - 24 h',
    tel: '806-510-1360',
    email: 'yizachikv@bizjournals.com',
    addr: {
      city: 'Pasto',
      street: 'Golf',
      houseNumber: '23',
    },
    webpageUrl: 'https://xrea.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00001f',
}, {
  name: 'Schowalter-Ward',
  type: 'Landscaping & Irrigation',
  description: 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in',
  contacts: {
    contactPerson: 'Wynn Mulqueeny',
    available: '0 - 24 h',
    tel: '456-914-3382',
    email: 'wmulqueenyw@fema.gov',
    addr: {
      city: 'Dowsk',
      street: 'Ramsey',
      houseNumber: '449',
    },
    webpageUrl: 'http://sina.com.cn',
  },
  active: true,
  uploader: '61182751fc13ae78fd000020',
}, {
  name: 'Predovic Group',
  type: 'Fire Protection',
  description: 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet',
  contacts: {
    contactPerson: 'Mitchell Partrick',
    available: '0 - 24 h',
    tel: '695-907-7130',
    email: 'mpartrickx@diigo.com',
    addr: {
      city: 'Stavanger',
      street: 'Carberry',
      houseNumber: '87468',
    },
    webpageUrl: 'https://imdb.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000021',
}, {
  name: 'Jacobson, Purdy and Stroman',
  type: 'Structural and Misc Steel (Fabrication)',
  description: 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros',
  contacts: {
    contactPerson: 'Katee Doel',
    available: '0 - 24 h',
    tel: '762-424-7616',
    email: 'kdoely@mtv.com',
    addr: {
      city: 'Dalmatovo',
      street: 'Bluestem',
      houseNumber: '432',
    },
    webpageUrl: 'https://alexa.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000022',
}, {
  name: 'Blick-Cruickshank',
  type: 'Sitework & Site Utilities',
  description: 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio',
  contacts: {
    contactPerson: 'Tobias Markwell',
    available: '0 - 24 h',
    tel: '426-633-7300',
    email: 'tmarkwellz@senate.gov',
    addr: {
      city: 'Bègles',
      street: 'Paget',
      houseNumber: '5800',
    },
    webpageUrl: 'http://xrea.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000023',
}, {
  name: 'Welch Group',
  type: 'Casework',
  description: 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a',
  contacts: {
    contactPerson: 'Josias Provost',
    available: '0 - 24 h',
    tel: '661-432-2529',
    email: 'jprovost10@google.co.uk',
    addr: {
      city: 'Jingyang',
      street: 'Maryland',
      houseNumber: '7415',
    },
    webpageUrl: 'https://pbs.org',
  },
  active: false,
  uploader: '61182751fc13ae78fd000024',
}, {
  name: 'Hegmann, Purdy and Sporer',
  type: 'Drywall & Acoustical (MOB)',
  description: 'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec',
  contacts: {
    contactPerson: 'Willamina Elvey',
    available: 'H-P: 8:00 - 16:00',
    tel: '642-252-9166',
    email: 'welvey11@senate.gov',
    addr: {
      city: 'Woshui',
      street: 'Stuart',
      houseNumber: '399',
    },
    webpageUrl: 'http://prweb.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000025',
}, {
  name: 'Larson and Sons',
  type: 'Framing (Wood)',
  description: 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio',
  contacts: {
    contactPerson: 'Ashli Breslauer',
    available: 'H-P: 8:00 - 16:00',
    tel: '147-190-2538',
    email: 'abreslauer12@alibaba.com',
    addr: {
      city: 'Tirat Karmel',
      street: 'Old Gate',
      houseNumber: '11865',
    },
    webpageUrl: 'https://people.com.cn',
  },
  active: false,
  uploader: '61182751fc13ae78fd000026',
}, {
  name: 'Johnson-Marks',
  type: 'Fire Protection',
  description: 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat',
  contacts: {
    contactPerson: 'Guilbert Maynard',
    available: 'H-P: 8:00 - 16:00',
    tel: '458-148-5596',
    email: 'gmaynard13@multiply.com',
    addr: {
      city: 'Žlutice',
      street: 'Melrose',
      houseNumber: '65',
    },
    webpageUrl: 'http://howstuffworks.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000027',
}, {
  name: 'Pagac, Nitzsche and Schiller',
  type: 'Roofing (Metal)',
  description: 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec',
  contacts: {
    contactPerson: 'Randal Cuddihy',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '682-464-6414',
    email: 'rcuddihy14@amazonaws.com',
    addr: {
      city: 'Jiedu',
      street: 'Chinook',
      houseNumber: '0',
    },
    webpageUrl: 'http://umn.edu',
  },
  active: true,
  uploader: '61182751fc13ae78fd000028',
}, {
  name: 'Miller, Thiel and Wolff',
  type: 'Sitework & Site Utilities',
  description: 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum',
  contacts: {
    contactPerson: 'Kain Gartell',
    available: '0 - 24 h',
    tel: '811-140-8271',
    email: 'kgartell15@washington.edu',
    addr: {
      city: 'Magutian',
      street: 'Tomscot',
      houseNumber: '500',
    },
    webpageUrl: 'https://ox.ac.uk',
  },
  active: false,
  uploader: '61182751fc13ae78fd000029',
}, {
  name: "Davis-O'Conner",
  type: 'Electrical and Fire Alarm',
  description: 'vitae mattis nibh ligula nec sem duis aliquam convallis nunc',
  contacts: {
    contactPerson: 'Nelson Boston',
    available: 'H-P: 8:00 - 16:00',
    tel: '699-453-0956',
    email: 'nboston16@bing.com',
    addr: {
      city: 'Storozhynets’',
      street: 'Crescent Oaks',
      houseNumber: '80034',
    },
    webpageUrl: 'https://blogtalkradio.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00002a',
}, {
  name: 'Simonis-Fadel',
  type: 'Fire Protection',
  description: 'massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis',
  contacts: {
    contactPerson: 'Addie Tidgewell',
    available: '0 - 24 h',
    tel: '769-801-7391',
    email: 'atidgewell17@ucoz.ru',
    addr: {
      city: 'Obo',
      street: 'Muir',
      houseNumber: '88663',
    },
    webpageUrl: 'https://nsw.gov.au',
  },
  active: false,
  uploader: '61182751fc13ae78fd00002b',
}, {
  name: 'Goyette-Ledner',
  type: 'Fire Sprinkler System',
  description: 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor',
  contacts: {
    contactPerson: 'Ewen Marzelli',
    available: '0 - 24 h',
    tel: '827-648-2351',
    email: 'emarzelli18@eventbrite.com',
    addr: {
      city: "Baie-D'Urfé",
      street: 'Pennsylvania',
      houseNumber: '91852',
    },
    webpageUrl: 'http://yale.edu',
  },
  active: true,
  uploader: '61182751fc13ae78fd00002c',
}, {
  name: 'Kub-Connelly',
  type: 'Marlite Panels (FED)',
  description: 'convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas',
  contacts: {
    contactPerson: 'Franz Chaston',
    available: '0 - 24 h',
    tel: '493-729-6149',
    email: 'fchaston19@theguardian.com',
    addr: {
      city: 'Malianchuan',
      street: 'Raven',
      houseNumber: '8',
    },
    webpageUrl: 'https://acquirethisname.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd00002d',
}, {
  name: 'Stanton, Russel and Hoeger',
  type: 'Rebar & Wire Mesh Install',
  description: 'mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a',
  contacts: {
    contactPerson: 'Anneliese Gawler',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '703-533-2992',
    email: 'agawler1a@people.com.cn',
    addr: {
      city: 'Kropotkin',
      street: 'Tomscot',
      houseNumber: '29823',
    },
    webpageUrl: 'https://yellowpages.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00002e',
}, {
  name: 'Mohr-Beatty',
  type: 'Masonry & Precast',
  description: 'ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla',
  contacts: {
    contactPerson: 'Garth Busse',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '757-223-6914',
    email: 'gbusse1b@alibaba.com',
    addr: {
      city: 'Balongmulyo',
      street: 'Acker',
      houseNumber: '807',
    },
    webpageUrl: 'http://foxnews.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00002f',
}, {
  name: 'Cassin-Kerluke',
  type: 'Temp Fencing, Decorative Fencing and Gates',
  description: 'sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel',
  contacts: {
    contactPerson: 'Rina Lum',
    available: '0 - 24 h',
    tel: '421-410-5334',
    email: 'rlum1c@sfgate.com',
    addr: {
      city: 'Los Frentones',
      street: 'Karstens',
      houseNumber: '15851',
    },
    webpageUrl: 'http://behance.net',
  },
  active: true,
  uploader: '61182751fc13ae78fd000030',
}, {
  name: 'Beier-Senger',
  type: 'Drilled Shafts',
  description: 'et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec',
  contacts: {
    contactPerson: 'Barnabas Zmitrichenko',
    available: '0 - 24 h',
    tel: '520-764-5940',
    email: 'bzmitrichenko1d@artisteer.com',
    addr: {
      city: 'San Francisco',
      street: 'Blaine',
      houseNumber: '75',
    },
    webpageUrl: 'http://microsoft.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000031',
}, {
  name: 'Lockman-Stamm',
  type: 'Casework',
  description: 'sit amet justo morbi ut odio cras mi pede malesuada in',
  contacts: {
    contactPerson: 'Jeromy Orleton',
    available: 'H-P: 8:00 - 16:00',
    tel: '547-267-8283',
    email: 'jorleton1e@hugedomains.com',
    addr: {
      city: 'Tominian',
      street: 'Spohn',
      houseNumber: '87419',
    },
    webpageUrl: 'http://digg.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000032',
}, {
  name: 'McDermott Inc',
  type: 'Plumbing & Medical Gas',
  description: 'mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede',
  contacts: {
    contactPerson: 'Starr Hun',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '642-172-0151',
    email: 'shun1f@java.com',
    addr: {
      city: 'Tambac',
      street: 'Burrows',
      houseNumber: '09',
    },
    webpageUrl: 'http://yellowbook.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000033',
}, {
  name: 'Gutkowski-Heidenreich',
  type: 'Granite Surfaces',
  description: 'id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus',
  contacts: {
    contactPerson: 'Falito Worsnup',
    available: '0 - 24 h',
    tel: '674-377-1919',
    email: 'fworsnup1g@cocolog-nifty.com',
    addr: {
      city: 'Vanadzor',
      street: 'Springs',
      houseNumber: '6241',
    },
    webpageUrl: 'https://technorati.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000034',
}, {
  name: 'Hammes-Pollich',
  type: 'Casework',
  description: 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla',
  contacts: {
    contactPerson: 'Tristam Eldred',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '726-764-9639',
    email: 'teldred1h@usa.gov',
    addr: {
      city: 'Panimbang',
      street: 'Melvin',
      houseNumber: '355',
    },
    webpageUrl: 'http://cnbc.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000035',
}, {
  name: 'Steuber, Pacocha and Altenwerth',
  type: 'Fire Sprinkler System',
  description: 'eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis',
  contacts: {
    contactPerson: 'Dewitt Scholfield',
    available: 'H-P: 8:00 - 16:00',
    tel: '597-440-9889',
    email: 'dscholfield1i@themeforest.net',
    addr: {
      city: 'Tongzhong',
      street: 'John Wall',
      houseNumber: '1',
    },
    webpageUrl: 'http://deliciousdays.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000036',
}, {
  name: 'Nader, Mante and Ullrich',
  type: 'Electrical',
  description: 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia',
  contacts: {
    contactPerson: 'Blisse Marielle',
    available: 'H-P: 8:00 - 16:00',
    tel: '317-278-7767',
    email: 'bmarielle1j@hexun.com',
    addr: {
      city: 'El Rincón',
      street: 'Trailsway',
      houseNumber: '871',
    },
    webpageUrl: 'http://chron.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000037',
}, {
  name: 'Stokes-Harber',
  type: 'EIFS',
  description: 'odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est',
  contacts: {
    contactPerson: 'Natalee Nund',
    available: '0 - 24 h',
    tel: '387-546-8461',
    email: 'nnund1k@narod.ru',
    addr: {
      city: 'Gao’an',
      street: 'Esker',
      houseNumber: '1528',
    },
    webpageUrl: 'http://bloglines.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000038',
}, {
  name: 'Rippin and Sons',
  type: 'Doors, Frames & Hardware',
  description: 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus',
  contacts: {
    contactPerson: 'Krystal Von Salzberg',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '447-858-4065',
    email: 'kvon1l@loc.gov',
    addr: {
      city: 'Luyang',
      street: 'Westerfield',
      houseNumber: '929',
    },
    webpageUrl: 'http://issuu.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000039',
}, {
  name: 'Heller-Hermann',
  type: 'Overhead Doors',
  description: 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent',
  contacts: {
    contactPerson: 'Vonni Lorking',
    available: 'H-P: 8:00 - 16:00',
    tel: '689-385-8451',
    email: 'vlorking1m@usnews.com',
    addr: {
      city: 'Panenggoede',
      street: 'Grim',
      houseNumber: '5',
    },
    webpageUrl: 'https://sphinn.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd00003a',
}, {
  name: 'Robel and Sons',
  type: 'Hard Tile & Stone',
  description: 'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam',
  contacts: {
    contactPerson: 'Baillie Caple',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '829-487-0339',
    email: 'bcaple1n@blogtalkradio.com',
    addr: {
      city: 'Tangnanzhen',
      street: 'Basil',
      houseNumber: '15',
    },
    webpageUrl: 'https://people.com.cn',
  },
  active: true,
  uploader: '61182751fc13ae78fd00003b',
}, {
  name: 'Hayes and Sons',
  type: 'Hard Tile & Stone',
  description: 'in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt',
  contacts: {
    contactPerson: 'Elisabet Vallack',
    available: 'H-P: 8:00 - 16:00',
    tel: '850-234-2165',
    email: 'evallack1o@mit.edu',
    addr: {
      city: 'Jistebník',
      street: 'Duke',
      houseNumber: '1626',
    },
    webpageUrl: 'https://yellowbook.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd00003c',
}, {
  name: 'Beahan, Schiller and Harris',
  type: 'Wall Protection',
  description: 'luctus cum sociis natoque penatibus et magnis dis parturient montes',
  contacts: {
    contactPerson: 'Jordan Stutte',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '215-589-1155',
    email: 'jstutte1p@drupal.org',
    addr: {
      city: 'Sulang Tengah',
      street: 'Bashford',
      houseNumber: '241',
    },
    webpageUrl: 'http://live.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00003d',
}, {
  name: 'Hodkiewicz, Goldner and Veum',
  type: 'Retaining Wall and Brick Pavers',
  description: 'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus',
  contacts: {
    contactPerson: 'Hana Ings',
    available: '0 - 24 h',
    tel: '703-487-0401',
    email: 'hings1q@wiley.com',
    addr: {
      city: 'Beskolen',
      street: 'Mcbride',
      houseNumber: '1760',
    },
    webpageUrl: 'https://arizona.edu',
  },
  active: false,
  uploader: '61182751fc13ae78fd00003e',
}, {
  name: 'Christiansen Group',
  type: 'Prefabricated Aluminum Metal Canopies',
  description: 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl',
  contacts: {
    contactPerson: 'Joya Desport',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '988-451-0485',
    email: 'jdesport1r@spotify.com',
    addr: {
      city: 'El Valle del Espíritu Santo',
      street: 'Myrtle',
      houseNumber: '9212',
    },
    webpageUrl: 'https://theatlantic.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd00003f',
}, {
  name: 'Paucek, Carroll and Schuster',
  type: 'RF Shielding',
  description: 'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit',
  contacts: {
    contactPerson: 'Goober Howat',
    available: '0 - 24 h',
    tel: '882-300-4284',
    email: 'ghowat1s@howstuffworks.com',
    addr: {
      city: 'Xinxu',
      street: 'Vernon',
      houseNumber: '49',
    },
    webpageUrl: 'http://cnbc.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000040',
}, {
  name: 'Larson-Torp',
  type: 'Retaining Wall and Brick Pavers',
  description: 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer',
  contacts: {
    contactPerson: 'Aksel Escofier',
    available: 'H-P: 8:00 - 16:00',
    tel: '681-765-8048',
    email: 'aescofier1t@yahoo.co.jp',
    addr: {
      city: 'Vermelha',
      street: 'Victoria',
      houseNumber: '87',
    },
    webpageUrl: 'https://techcrunch.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000041',
}, {
  name: 'Hessel-Keebler',
  type: 'Ornamental Railings',
  description: 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat',
  contacts: {
    contactPerson: 'Dedra Gimblett',
    available: 'H-P: 8:00 - 16:00',
    tel: '201-938-9813',
    email: 'dgimblett1u@furl.net',
    addr: {
      city: 'Kristiansand S',
      street: 'Veith',
      houseNumber: '49569',
    },
    webpageUrl: 'https://springer.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000042',
}, {
  name: 'Lang, Bins and Mohr',
  type: 'Granite Surfaces',
  description: 'in hac habitasse platea dictumst etiam faucibus cursus urna ut',
  contacts: {
    contactPerson: 'Karia Niccolls',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '975-210-2413',
    email: 'kniccolls1v@desdev.cn',
    addr: {
      city: 'Yeniugou',
      street: 'Northport',
      houseNumber: '354',
    },
    webpageUrl: 'https://miibeian.gov.cn',
  },
  active: false,
  uploader: '61182751fc13ae78fd000043',
}, {
  name: 'Kerluke-Fisher',
  type: 'Drilled Shafts',
  description: 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at',
  contacts: {
    contactPerson: 'Vinnie Lidster',
    available: '0 - 24 h',
    tel: '883-140-8058',
    email: 'vlidster1w@wix.com',
    addr: {
      city: 'Constanza',
      street: 'Forest',
      houseNumber: '422',
    },
    webpageUrl: 'https://nih.gov',
  },
  active: true,
  uploader: '61182751fc13ae78fd000044',
}, {
  name: 'Treutel-Crooks',
  type: 'RF Shielding',
  description: 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque',
  contacts: {
    contactPerson: 'Zach Hogbin',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '216-455-6574',
    email: 'zhogbin1x@stanford.edu',
    addr: {
      city: 'Jaguarão',
      street: 'Fisk',
      houseNumber: '17',
    },
    webpageUrl: 'https://telegraph.co.uk',
  },
  active: false,
  uploader: '61182751fc13ae78fd000045',
}, {
  name: 'Spinka Inc',
  type: 'EIFS',
  description: 'vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum',
  contacts: {
    contactPerson: 'Asher Kemitt',
    available: 'H-P: 8:00 - 16:00',
    tel: '644-600-3776',
    email: 'akemitt1y@tinyurl.com',
    addr: {
      city: 'Canguçu',
      street: 'Bowman',
      houseNumber: '43',
    },
    webpageUrl: 'http://ustream.tv',
  },
  active: false,
  uploader: '61182751fc13ae78fd000046',
}, {
  name: 'Medhurst, Koepp and Graham',
  type: 'EIFS',
  description: 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus',
  contacts: {
    contactPerson: 'Claudette Vondruska',
    available: '0 - 24 h',
    tel: '160-180-9701',
    email: 'cvondruska1z@npr.org',
    addr: {
      city: 'Yinjiang',
      street: 'Macpherson',
      houseNumber: '9',
    },
    webpageUrl: 'http://arstechnica.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000047',
}, {
  name: 'Kuvalis Group',
  type: 'Epoxy Flooring',
  description: 'non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus',
  contacts: {
    contactPerson: 'Retha Murrhardt',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '916-580-5652',
    email: 'rmurrhardt20@indiegogo.com',
    addr: {
      city: 'Sacramento',
      street: 'Farwell',
      houseNumber: '017',
    },
    webpageUrl: 'http://timesonline.co.uk',
  },
  active: true,
  uploader: '61182751fc13ae78fd000048',
}, {
  name: 'Nienow, Lakin and Quigley',
  type: 'Termite Control',
  description: 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum',
  contacts: {
    contactPerson: 'Natale Ranahan',
    available: '0 - 24 h',
    tel: '983-715-4138',
    email: 'nranahan21@vimeo.com',
    addr: {
      city: 'Nong Bun Nak',
      street: 'Lake View',
      houseNumber: '81',
    },
    webpageUrl: 'https://clickbank.net',
  },
  active: false,
  uploader: '61182751fc13ae78fd000049',
}, {
  name: 'Jast, Labadie and Mueller',
  type: 'Overhead Doors',
  description: 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque',
  contacts: {
    contactPerson: 'Bert Beer',
    available: '0 - 24 h',
    tel: '866-877-6888',
    email: 'bbeer22@netscape.com',
    addr: {
      city: 'Catarman',
      street: 'Oakridge',
      houseNumber: '6427',
    },
    webpageUrl: 'http://yandex.ru',
  },
  active: true,
  uploader: '61182751fc13ae78fd00004a',
}, {
  name: 'Cummerata, Cassin and Gerhold',
  type: 'Ornamental Railings',
  description: 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce',
  contacts: {
    contactPerson: 'Fredrick Fortie',
    available: 'H-P: 8:00 - 16:00',
    tel: '814-477-2709',
    email: 'ffortie23@drupal.org',
    addr: {
      city: 'Chemnitz',
      street: 'Holy Cross',
      houseNumber: '36120',
    },
    webpageUrl: 'https://hostgator.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00004b',
}, {
  name: 'Kirlin-Okuneva',
  type: 'Electrical and Fire Alarm',
  description: 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a',
  contacts: {
    contactPerson: 'Nat McGreil',
    available: '0 - 24 h',
    tel: '257-657-9436',
    email: 'nmcgreil24@archive.org',
    addr: {
      city: 'Shixiang',
      street: 'Michigan',
      houseNumber: '6',
    },
    webpageUrl: 'http://businessweek.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00004c',
}, {
  name: 'Gutkowski Inc',
  type: 'Electrical',
  description: 'mi sit amet lobortis sapien sapien non mi integer ac',
  contacts: {
    contactPerson: 'Perrine Daen',
    available: 'H-P: 8:00 - 16:00',
    tel: '948-237-7747',
    email: 'pdaen25@google.de',
    addr: {
      city: 'Kajiki',
      street: 'Lindbergh',
      houseNumber: '947',
    },
    webpageUrl: 'http://symantec.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00004d',
}, {
  name: 'Ledner, Ebert and Keebler',
  type: 'Structural and Misc Steel (Fabrication)',
  description: 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus',
  contacts: {
    contactPerson: 'Micheal Vynehall',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '138-807-9780',
    email: 'mvynehall26@fda.gov',
    addr: {
      city: 'Ngaruawahia',
      street: 'Hoard',
      houseNumber: '88',
    },
    webpageUrl: 'https://51.la',
  },
  active: true,
  uploader: '61182751fc13ae78fd00004e',
}, {
  name: 'McKenzie LLC',
  type: 'Painting & Vinyl Wall Covering',
  description: 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula',
  contacts: {
    contactPerson: 'Northrop Donisi',
    available: 'H-P: 8:00 - 16:00',
    tel: '470-117-2641',
    email: 'ndonisi27@printfriendly.com',
    addr: {
      city: 'Masaraway',
      street: '6th',
      houseNumber: '795',
    },
    webpageUrl: 'https://dailymail.co.uk',
  },
  active: false,
  uploader: '61182751fc13ae78fd00004f',
}, {
  name: 'Goodwin-Bins',
  type: 'Structural and Misc Steel (Fabrication)',
  description: 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices',
  contacts: {
    contactPerson: 'Wright Shields',
    available: 'H-P: 8:00 - 16:00',
    tel: '312-155-1437',
    email: 'wshields28@uol.com.br',
    addr: {
      city: 'Chicago',
      street: 'Anzinger',
      houseNumber: '4',
    },
    webpageUrl: 'https://xinhuanet.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000050',
}, {
  name: 'Schumm, Rath and Wintheiser',
  type: 'Soft Flooring and Base',
  description: 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus',
  contacts: {
    contactPerson: 'Danita Mocquer',
    available: '0 - 24 h',
    tel: '452-686-2211',
    email: 'dmocquer29@discuz.net',
    addr: {
      city: 'Kruhlaye',
      street: 'Aberg',
      houseNumber: '85994',
    },
    webpageUrl: 'http://pagesperso-orange.fr',
  },
  active: true,
  uploader: '61182751fc13ae78fd000051',
}, {
  name: 'Ankunding LLC',
  type: 'Structural & Misc Steel Erection',
  description: 'fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien',
  contacts: {
    contactPerson: 'Elly Heinel',
    available: 'H-P: 8:00 - 16:00',
    tel: '411-462-3809',
    email: 'eheinel2a@furl.net',
    addr: {
      city: 'Lipin Bor',
      street: 'Mandrake',
      houseNumber: '6',
    },
    webpageUrl: 'https://upenn.edu',
  },
  active: true,
  uploader: '61182751fc13ae78fd000052',
}, {
  name: 'Boyer Group',
  type: 'Rebar & Wire Mesh Install',
  description: 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus',
  contacts: {
    contactPerson: 'Carlye Mazin',
    available: '0 - 24 h',
    tel: '336-288-5076',
    email: 'cmazin2b@tiny.cc',
    addr: {
      city: 'Kae Dam',
      street: 'Esch',
      houseNumber: '0758',
    },
    webpageUrl: 'https://barnesandnoble.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000053',
}, {
  name: 'Nitzsche Inc',
  type: 'Curb & Gutter',
  description: 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit',
  contacts: {
    contactPerson: 'Barbara Getley',
    available: '0 - 24 h',
    tel: '524-718-8222',
    email: 'bgetley2c@telegraph.co.uk',
    addr: {
      city: 'Randfontein',
      street: 'Lawn',
      houseNumber: '08',
    },
    webpageUrl: 'http://chron.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000054',
}, {
  name: 'Simonis LLC',
  type: 'Framing (Wood)',
  description: 'amet eleifend pede libero quis orci nullam molestie nibh in lectus',
  contacts: {
    contactPerson: 'Lorens Concannon',
    available: '0 - 24 h',
    tel: '668-546-9131',
    email: 'lconcannon2d@de.vu',
    addr: {
      city: 'Winneba',
      street: 'Northland',
      houseNumber: '002',
    },
    webpageUrl: 'http://netlog.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000055',
}, {
  name: 'Leffler-Bashirian',
  type: 'RF Shielding',
  description: 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla',
  contacts: {
    contactPerson: 'Lisha Elphick',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '968-408-7508',
    email: 'lelphick2e@cafepress.com',
    addr: {
      city: 'Wanliang',
      street: 'Clarendon',
      houseNumber: '26',
    },
    webpageUrl: 'http://sun.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000056',
}, {
  name: 'Conn, Breitenberg and Stracke',
  type: 'Drywall & Acoustical (FED)',
  description: 'vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit',
  contacts: {
    contactPerson: 'Brian Samter',
    available: 'H-P: 8:00 - 16:00',
    tel: '388-134-6654',
    email: 'bsamter2f@elpais.com',
    addr: {
      city: 'Prienai',
      street: 'Barnett',
      houseNumber: '44147',
    },
    webpageUrl: 'https://bloglovin.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000057',
}, {
  name: 'Oberbrunner, Kemmer and Yost',
  type: 'Waterproofing & Caulking',
  description: 'nec sem duis aliquam convallis nunc proin at turpis a pede posuere',
  contacts: {
    contactPerson: 'Jaye Balazs',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '148-189-3324',
    email: 'jbalazs2g@state.tx.us',
    addr: {
      city: 'Meiyuan Xincun',
      street: 'Sachtjen',
      houseNumber: '1',
    },
    webpageUrl: 'https://last.fm',
  },
  active: false,
  uploader: '61182751fc13ae78fd000058',
}, {
  name: 'Hahn, Hyatt and McKenzie',
  type: 'Drywall & Acoustical (MOB)',
  description: 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus',
  contacts: {
    contactPerson: 'Zara Boole',
    available: '0 - 24 h',
    tel: '729-542-6730',
    email: 'zboole2h@salon.com',
    addr: {
      city: 'Magadan',
      street: 'Oxford',
      houseNumber: '232',
    },
    webpageUrl: 'http://hexun.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd000059',
}, {
  name: 'Weissnat-Grant',
  type: 'Granite Surfaces',
  description: 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum',
  contacts: {
    contactPerson: 'Aristotle Chinnock',
    available: 'H-P: 8:00 - 16:00',
    tel: '468-540-6806',
    email: 'achinnock2i@bigcartel.com',
    addr: {
      city: 'Machida',
      street: 'Schiller',
      houseNumber: '2',
    },
    webpageUrl: 'https://marketwatch.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00005a',
}, {
  name: "Wintheiser, Fisher and O'Kon",
  type: 'Roofing (Metal)',
  description: 'ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in',
  contacts: {
    contactPerson: 'Risa Hankin',
    available: 'H-P: 8:00 - 16:00',
    tel: '686-635-1098',
    email: 'rhankin2j@sciencedaily.com',
    addr: {
      city: 'Grybów',
      street: 'Loomis',
      houseNumber: '4358',
    },
    webpageUrl: 'http://about.me',
  },
  active: true,
  uploader: '61182751fc13ae78fd00005b',
}, {
  name: 'Abshire, Bogisich and Emmerich',
  type: 'Epoxy Flooring',
  description: 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in',
  contacts: {
    contactPerson: 'Jamima Lodewick',
    available: '0 - 24 h',
    tel: '386-975-8966',
    email: 'jlodewick2k@cocolog-nifty.com',
    addr: {
      city: 'Chile Chico',
      street: 'Dorton',
      houseNumber: '64',
    },
    webpageUrl: 'http://surveymonkey.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00005c',
}, {
  name: 'Nader, Lang and Reilly',
  type: 'HVAC',
  description: 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo',
  contacts: {
    contactPerson: 'Lennie Braney',
    available: '0 - 24 h',
    tel: '135-741-9593',
    email: 'lbraney2l@amazonaws.com',
    addr: {
      city: 'Swindon',
      street: 'Union',
      houseNumber: '56',
    },
    webpageUrl: 'http://ihg.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd00005d',
}, {
  name: 'Wolf Inc',
  type: 'Rebar & Wire Mesh Install',
  description: 'in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum',
  contacts: {
    contactPerson: 'Darnall Demko',
    available: 'H-P: 8:00 - 16:00',
    tel: '243-519-5209',
    email: 'ddemko2m@oakley.com',
    addr: {
      city: 'Sutysky',
      street: 'Meadow Vale',
      houseNumber: '72',
    },
    webpageUrl: 'https://unblog.fr',
  },
  active: false,
  uploader: '61182751fc13ae78fd00005e',
}, {
  name: 'Cassin Inc',
  type: 'Fire Sprinkler System',
  description: 'potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue',
  contacts: {
    contactPerson: 'Shepard Bellas',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '173-552-0821',
    email: 'sbellas2n@friendfeed.com',
    addr: {
      city: 'Jakobstad',
      street: 'Johnson',
      houseNumber: '14',
    },
    webpageUrl: 'https://linkedin.com',
  },
  active: false,
  uploader: '61182751fc13ae78fd00005f',
}, {
  name: 'Anderson LLC',
  type: 'Soft Flooring and Base',
  description: 'eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum',
  contacts: {
    contactPerson: 'Orella Bullan',
    available: 'H-Szo: 8:00 - 20:00',
    tel: '214-931-4380',
    email: 'obullan2o@telegraph.co.uk',
    addr: {
      city: 'Wonotirto',
      street: 'Acker',
      houseNumber: '9',
    },
    webpageUrl: 'https://1688.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000060',
}, {
  name: 'Monahan, Frami and Kuhlman',
  type: 'Framing (Steel)',
  description: 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id',
  contacts: {
    contactPerson: 'Pate Fulham',
    available: 'H-P: 8:00 - 16:00',
    tel: '691-995-1612',
    email: 'pfulham2p@elpais.com',
    addr: {
      city: 'Avon',
      street: 'Eliot',
      houseNumber: '3274',
    },
    webpageUrl: 'https://liveinternet.ru',
  },
  active: false,
  uploader: '61182751fc13ae78fd000061',
}, {
  name: 'Abbott, Bayer and Jerde',
  type: 'HVAC',
  description: 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus',
  contacts: {
    contactPerson: 'Terese Woodvine',
    available: 'H-P: 8:00 - 16:00',
    tel: '146-973-6012',
    email: 'twoodvine2q@hugedomains.com',
    addr: {
      city: 'Turangi',
      street: 'Shasta',
      houseNumber: '5822',
    },
    webpageUrl: 'https://amazon.com',
  },
  active: true,
  uploader: '61182751fc13ae78fd000062',
}, {
  name: 'Kris Group',
  type: 'Drilled Shafts',
  description: 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed',
  contacts: {
    contactPerson: 'Ceil Stackbridge',
    available: 'H-P: 8:00 - 16:00',
    tel: '545-295-5816',
    email: 'cstackbridge2r@comcast.net',
    addr: {
      city: 'Nevinnomyssk',
      street: 'Lindbergh',
      houseNumber: '2430',
    },
    webpageUrl: 'https://nps.gov',
  },
  active: true,
  uploader: '61182751fc13ae78fd000063',
}];
