module.exports = [{
  firstName: 'admin',
  lastName: 'admino',
  email: 'admin@test.com',
  addr: {
    city: 'Montauban',
    street: 'Sachtjen',
    houseNumber: '0347',
  },
  password: 'admin_pw',
  active: true,
  role: 'admin',
}, {
  firstName: 'Vite',
  lastName: 'Laister',
  email: 'vlaister1@archive.org',
  addr: {
    city: 'Port Glaud',
    street: 'Ridgeway',
    houseNumber: '8',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Jeno',
  lastName: 'Moizer',
  email: 'jmoizer2@technorati.com',
  addr: {
    city: 'Doushaguan',
    street: 'Cottonwood',
    houseNumber: '5',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Carol-jean',
  lastName: 'Bocken',
  email: 'cbocken3@friendfeed.com',
  addr: {
    city: 'Colmar',
    street: 'Hallows',
    houseNumber: '8230',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Tove',
  lastName: 'Mongenot',
  email: 'tmongenot4@seesaa.net',
  addr: {
    city: 'Daxindian',
    street: 'Lyons',
    houseNumber: '967',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Gerri',
  lastName: 'Feltoe',
  email: 'gfeltoe5@princeton.edu',
  addr: {
    city: 'Ubaté',
    street: 'Monterey',
    houseNumber: '10',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Jenda',
  lastName: 'Ordish',
  email: 'jordish6@prweb.com',
  addr: {
    city: 'Bagong Sikat',
    street: 'Lawn',
    houseNumber: '66303',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Burnaby',
  lastName: 'Larwood',
  email: 'blarwood7@tiny.cc',
  addr: {
    city: 'Jesús María',
    street: 'Porter',
    houseNumber: '875',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Dyanne',
  lastName: 'Argabrite',
  email: 'dargabrite8@sourceforge.net',
  addr: {
    city: 'Centro Habana',
    street: 'Corben',
    houseNumber: '7',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Jordon',
  lastName: 'McInulty',
  email: 'jmcinulty9@nbcnews.com',
  addr: {
    city: 'Laweueng',
    street: 'Miller',
    houseNumber: '52',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Rutherford',
  lastName: 'Grenter',
  email: 'rgrentera@diigo.com',
  addr: {
    city: 'Luis Donaldo Colosio',
    street: 'Westridge',
    houseNumber: '8',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Brigitta',
  lastName: "O'Teague",
  email: 'boteagueb@icq.com',
  addr: {
    city: 'Połajewo',
    street: 'Gina',
    houseNumber: '4387',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Dione',
  lastName: 'Pechan',
  email: 'dpechanc@about.me',
  addr: {
    city: 'Cidima',
    street: 'Norway Maple',
    houseNumber: '53',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Man',
  lastName: 'Fairlie',
  email: 'mfairlied@tiny.cc',
  addr: {
    city: 'Nhà Bè',
    street: 'Holy Cross',
    houseNumber: '663',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Dulcea',
  lastName: 'Watsam',
  email: 'dwatsame@guardian.co.uk',
  addr: {
    city: 'Bagjasari',
    street: 'Hovde',
    houseNumber: '2166',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Jonah',
  lastName: 'Rash',
  email: 'jrashf@illinois.edu',
  addr: {
    city: 'Berezivka',
    street: 'Loeprich',
    houseNumber: '408',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Penelopa',
  lastName: 'Guerrin',
  email: 'pguerring@engadget.com',
  addr: {
    city: 'Victoria',
    street: 'Southridge',
    houseNumber: '60400',
  },
  password: 'test',
  active: true,
  role: 'user',
}, {
  firstName: 'Valenka',
  lastName: 'Peaden',
  email: 'vpeadenh@zimbio.com',
  addr: {
    city: 'Parthenay',
    street: 'Schlimgen',
    houseNumber: '032',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Bronnie',
  lastName: 'Jedrzejewsky',
  email: 'bjedrzejewskyi@nba.com',
  addr: {
    city: 'Arras',
    street: 'Independence',
    houseNumber: '6',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Pete',
  lastName: 'Klas',
  email: 'pklasj@umich.edu',
  addr: {
    city: 'Sendafa',
    street: 'Merry',
    houseNumber: '506',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Stacia',
  lastName: 'Benninger',
  email: 'sbenningerk@samsung.com',
  addr: {
    city: 'Laval',
    street: 'Sundown',
    houseNumber: '557',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Godard',
  lastName: 'Corballis',
  email: 'gcorballisl@ucla.edu',
  addr: {
    city: 'Pridonskoy',
    street: 'Talmadge',
    houseNumber: '18',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Boris',
  lastName: 'De Cruze',
  email: 'bdecruzem@bandcamp.com',
  addr: {
    city: 'Itapuranga',
    street: 'Westridge',
    houseNumber: '69',
  },
  password: 'test',
  active: true,
  role: 'user',
}, {
  firstName: 'Kippy',
  lastName: 'Jouanet',
  email: 'kjouanetn@ezinearticles.com',
  addr: {
    city: 'Rancaseneng',
    street: 'Stuart',
    houseNumber: '1',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Hadlee',
  lastName: 'Harmond',
  email: 'hharmondo@com.com',
  addr: {
    city: 'Costa de Rios Frios',
    street: 'Graedel',
    houseNumber: '20020',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Jemima',
  lastName: 'Meriel',
  email: 'jmerielp@flavors.me',
  addr: {
    city: 'Gala',
    street: 'Village Green',
    houseNumber: '76059',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Percy',
  lastName: 'Samsin',
  email: 'psamsinq@opensource.org',
  addr: {
    city: 'Simajia',
    street: 'Hoffman',
    houseNumber: '07',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Salmon',
  lastName: 'Lukas',
  email: 'slukasr@merriam-webster.com',
  addr: {
    city: 'Makar’yev',
    street: 'Crest Line',
    houseNumber: '1947',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Joby',
  lastName: 'Sprigging',
  email: 'jspriggings@quantcast.com',
  addr: {
    city: 'Wuluquele',
    street: 'Schiller',
    houseNumber: '6635',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Meara',
  lastName: 'Ahren',
  email: 'mahrent@constantcontact.com',
  addr: {
    city: 'Francisco Sarabia',
    street: 'Nobel',
    houseNumber: '14527',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Munroe',
  lastName: 'Budnik',
  email: 'mbudniku@oracle.com',
  addr: {
    city: 'Thị Trấn Na Hang',
    street: 'Hansons',
    houseNumber: '4',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Maddy',
  lastName: 'Ivy',
  email: 'mivyv@yandex.ru',
  addr: {
    city: 'Santa Apolonia',
    street: 'Northridge',
    houseNumber: '26569',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Henderson',
  lastName: 'Gathercoal',
  email: 'hgathercoalw@google.de',
  addr: {
    city: 'København',
    street: 'Barnett',
    houseNumber: '89249',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Dorie',
  lastName: 'Reddy',
  email: 'dreddyx@diigo.com',
  addr: {
    city: 'Montpellier',
    street: 'Anhalt',
    houseNumber: '65293',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Harriett',
  lastName: 'Baudet',
  email: 'hbaudety@oaic.gov.au',
  addr: {
    city: 'Lengshui',
    street: 'Westport',
    houseNumber: '1',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Ernesta',
  lastName: 'Godbert',
  email: 'egodbertz@google.com.br',
  addr: {
    city: 'Tambo Grande',
    street: 'Evergreen',
    houseNumber: '11',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Kevyn',
  lastName: 'Tolland',
  email: 'ktolland10@businessinsider.com',
  addr: {
    city: 'Lokwabe',
    street: 'Buena Vista',
    houseNumber: '81',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Rosanna',
  lastName: 'Maffin',
  email: 'rmaffin11@desdev.cn',
  addr: {
    city: 'Ajaccio',
    street: 'Spenser',
    houseNumber: '9',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Langston',
  lastName: 'Blanche',
  email: 'lblanche12@sogou.com',
  addr: {
    city: 'Dongxiao',
    street: 'Pond',
    houseNumber: '3',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Edgard',
  lastName: 'McReath',
  email: 'emcreath13@walmart.com',
  addr: {
    city: 'Yancheng',
    street: 'Autumn Leaf',
    houseNumber: '738',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Ham',
  lastName: 'Ertel',
  email: 'hertel14@oakley.com',
  addr: {
    city: 'Phon Phisai',
    street: 'Meadow Ridge',
    houseNumber: '01728',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Dalis',
  lastName: 'Volcker',
  email: 'dvolcker15@homestead.com',
  addr: {
    city: 'Sirindhorn',
    street: 'Esch',
    houseNumber: '2116',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Dag',
  lastName: 'Hampstead',
  email: 'dhampstead16@a8.net',
  addr: {
    city: 'Yisa',
    street: 'Golden Leaf',
    houseNumber: '53',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Josefina',
  lastName: 'Moles',
  email: 'jmoles17@ycombinator.com',
  addr: {
    city: 'Göteborg',
    street: 'Aberg',
    houseNumber: '20641',
  },
  password: 'test',
  active: true,
  role: 'user',
}, {
  firstName: 'Riva',
  lastName: 'Gingold',
  email: 'rgingold18@miibeian.gov.cn',
  addr: {
    city: 'Kwangju',
    street: 'Lyons',
    houseNumber: '60',
  },
  password: 'test',
  active: true,
  role: 'user',
}, {
  firstName: 'Neala',
  lastName: 'Gabey',
  email: 'ngabey19@privacy.gov.au',
  addr: {
    city: 'Ostrów Wielkopolski',
    street: 'Bunting',
    houseNumber: '99168',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Shurwood',
  lastName: 'Knott',
  email: 'sknott1a@slideshare.net',
  addr: {
    city: 'Nagoya-shi',
    street: 'Anderson',
    houseNumber: '4',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Tallou',
  lastName: 'Richardet',
  email: 'trichardet1b@toplist.cz',
  addr: {
    city: 'Islāmkot',
    street: 'Messerschmidt',
    houseNumber: '61738',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Rafaelita',
  lastName: 'Jaggers',
  email: 'rjaggers1c@go.com',
  addr: {
    city: 'Bakov nad Jizerou',
    street: 'Eagan',
    houseNumber: '98',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Colin',
  lastName: 'Gerram',
  email: 'cgerram1d@economist.com',
  addr: {
    city: 'Golovchino',
    street: 'Dapin',
    houseNumber: '93',
  },
  password: 'test',
  active: true,
  role: 'user',
}, {
  firstName: 'Cathyleen',
  lastName: 'Bussell',
  email: 'cbussell1e@shareasale.com',
  addr: {
    city: 'Metsovo',
    street: 'Packers',
    houseNumber: '2',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Waylin',
  lastName: 'Goldsack',
  email: 'wgoldsack1f@elpais.com',
  addr: {
    city: 'Paucar',
    street: 'Northfield',
    houseNumber: '9604',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Ondrea',
  lastName: 'Happert',
  email: 'ohappert1g@yellowpages.com',
  addr: {
    city: 'Yunxian Chengguanzhen',
    street: 'Dunning',
    houseNumber: '3',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Doretta',
  lastName: 'Hammerman',
  email: 'dhammerman1h@jimdo.com',
  addr: {
    city: 'Li’an',
    street: 'Blaine',
    houseNumber: '55544',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Wayne',
  lastName: 'Sonier',
  email: 'wsonier1i@yelp.com',
  addr: {
    city: 'Lambayong',
    street: 'South',
    houseNumber: '5558',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Kenny',
  lastName: 'Blacksell',
  email: 'kblacksell1j@devhub.com',
  addr: {
    city: 'Pskov',
    street: 'Holmberg',
    houseNumber: '78',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Katleen',
  lastName: 'Prior',
  email: 'kprior1k@census.gov',
  addr: {
    city: 'Los Boquerones',
    street: 'Thierer',
    houseNumber: '2443',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Sadella',
  lastName: 'Bearn',
  email: 'sbearn1l@t-online.de',
  addr: {
    city: 'Panamá',
    street: 'Mitchell',
    houseNumber: '079',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Regina',
  lastName: 'Boffey',
  email: 'rboffey1m@behance.net',
  addr: {
    city: 'Changuillo',
    street: 'Saint Paul',
    houseNumber: '88647',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Phillip',
  lastName: 'Sommerlie',
  email: 'psommerlie1n@cocolog-nifty.com',
  addr: {
    city: 'Wushan',
    street: 'Golden Leaf',
    houseNumber: '8',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Tadd',
  lastName: 'Laugier',
  email: 'tlaugier1o@intel.com',
  addr: {
    city: 'Xiachen',
    street: 'Eagan',
    houseNumber: '022',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Keene',
  lastName: 'Pinsent',
  email: 'kpinsent1p@ning.com',
  addr: {
    city: 'Vidnoye',
    street: 'Upham',
    houseNumber: '5',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Lynnelle',
  lastName: 'Briscam',
  email: 'lbriscam1q@digg.com',
  addr: {
    city: 'Kabir',
    street: 'John Wall',
    houseNumber: '9',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Nicolina',
  lastName: 'Diben',
  email: 'ndiben1r@dot.gov',
  addr: {
    city: 'Montería',
    street: 'Kingsford',
    houseNumber: '050',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Gina',
  lastName: 'Gebbie',
  email: 'ggebbie1s@trellian.com',
  addr: {
    city: 'San Luis',
    street: 'Becker',
    houseNumber: '604',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Sibby',
  lastName: 'Giuroni',
  email: 'sgiuroni1t@google.es',
  addr: {
    city: 'Kawasaki',
    street: 'Towne',
    houseNumber: '389',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Brenn',
  lastName: 'Tate',
  email: 'btate1u@wikimedia.org',
  addr: {
    city: 'Āsbe Teferī',
    street: 'Old Shore',
    houseNumber: '3925',
  },
  password: 'test',
  active: true,
  role: 'user',
}, {
  firstName: 'Gaston',
  lastName: 'Vaines',
  email: 'gvaines1v@ameblo.jp',
  addr: {
    city: 'Vällingby',
    street: 'Bellgrove',
    houseNumber: '55',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Klaus',
  lastName: 'Innot',
  email: 'kinnot1w@wsj.com',
  addr: {
    city: 'An Lão',
    street: 'Spohn',
    houseNumber: '487',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Paco',
  lastName: 'Baskwell',
  email: 'pbaskwell1x@msu.edu',
  addr: {
    city: 'Sukaraja',
    street: 'Emmet',
    houseNumber: '24',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Callie',
  lastName: 'Garmans',
  email: 'cgarmans1y@freewebs.com',
  addr: {
    city: 'Soho',
    street: 'Pearson',
    houseNumber: '6',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Nichol',
  lastName: 'Saw',
  email: 'nsaw1z@google.pl',
  addr: {
    city: 'Wŏnju',
    street: 'Park Meadow',
    houseNumber: '4653',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Constancy',
  lastName: 'Castiglio',
  email: 'ccastiglio20@spiegel.de',
  addr: {
    city: 'Bomadi',
    street: 'Fieldstone',
    houseNumber: '8923',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Randolf',
  lastName: 'Colnet',
  email: 'rcolnet21@dyndns.org',
  addr: {
    city: 'Oslo',
    street: 'Ilene',
    houseNumber: '5',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Farica',
  lastName: 'Rodgerson',
  email: 'frodgerson22@google.fr',
  addr: {
    city: 'Henglan',
    street: 'Dwight',
    houseNumber: '2',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Dana',
  lastName: 'Sainter',
  email: 'dsainter23@about.me',
  addr: {
    city: 'Paris 10',
    street: 'Cambridge',
    houseNumber: '80',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Birch',
  lastName: 'Moffet',
  email: 'bmoffet24@ameblo.jp',
  addr: {
    city: 'Zhigalovo',
    street: 'Sunnyside',
    houseNumber: '2414',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Maiga',
  lastName: 'Cubberley',
  email: 'mcubberley25@google.it',
  addr: {
    city: 'Gombong',
    street: 'Farmco',
    houseNumber: '41913',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Lezlie',
  lastName: 'Pratley',
  email: 'lpratley26@technorati.com',
  addr: {
    city: 'Martinópolis',
    street: 'Michigan',
    houseNumber: '142',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Joella',
  lastName: 'Sammars',
  email: 'jsammars27@hc360.com',
  addr: {
    city: 'Uppsala',
    street: 'Northview',
    houseNumber: '38228',
  },
  password: 'test',
  active: true,
  role: 'user',
}, {
  firstName: 'Bessy',
  lastName: 'Cohani',
  email: 'bcohani28@marriott.com',
  addr: {
    city: 'Valencia',
    street: 'Everett',
    houseNumber: '4218',
  },
  password: 'test',
  active: true,
  role: 'user',
}, {
  firstName: 'Ray',
  lastName: 'Richardet',
  email: 'rrichardet29@dropbox.com',
  addr: {
    city: 'Burgos',
    street: 'Declaration',
    houseNumber: '022',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Florenza',
  lastName: 'Spohrmann',
  email: 'fspohrmann2a@utexas.edu',
  addr: {
    city: 'Creil',
    street: 'Chive',
    houseNumber: '151',
  },
  password: 'test',
  active: true,
  role: 'user',
}, {
  firstName: 'Sharla',
  lastName: 'Bence',
  email: 'sbence2b@nasa.gov',
  addr: {
    city: 'Indralayang',
    street: 'Donald',
    houseNumber: '6',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Aubree',
  lastName: 'Maciunas',
  email: 'amaciunas2c@si.edu',
  addr: {
    city: 'San Rafael',
    street: 'Schlimgen',
    houseNumber: '29374',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Gracie',
  lastName: 'Boffin',
  email: 'gboffin2d@about.me',
  addr: {
    city: 'Włoszczowa',
    street: 'Heffernan',
    houseNumber: '4221',
  },
  password: 'test',
  active: true,
  role: 'admin',
}, {
  firstName: 'Bili',
  lastName: 'Meadows',
  email: 'bmeadows2e@jigsy.com',
  addr: {
    city: 'Patemon',
    street: 'Truax',
    houseNumber: '7',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Lydon',
  lastName: 'Treen',
  email: 'ltreen2f@miitbeian.gov.cn',
  addr: {
    city: 'Dessalines',
    street: 'Waywood',
    houseNumber: '5',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Casie',
  lastName: 'Pauls',
  email: 'cpauls2g@cpanel.net',
  addr: {
    city: 'Knivsta',
    street: 'Village',
    houseNumber: '5221',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Eartha',
  lastName: 'Gavey',
  email: 'egavey2h@howstuffworks.com',
  addr: {
    city: 'Wanjia',
    street: 'Pepper Wood',
    houseNumber: '4880',
  },
  password: 'test',
  active: true,
  role: 'user',
}, {
  firstName: 'Deerdre',
  lastName: 'Ding',
  email: 'dding2i@hexun.com',
  addr: {
    city: 'Babakan',
    street: 'Sunnyside',
    houseNumber: '3594',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Easter',
  lastName: 'Voas',
  email: 'evoas2j@phpbb.com',
  addr: {
    city: 'Borek',
    street: 'Gale',
    houseNumber: '265',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Aurelie',
  lastName: 'Keegan',
  email: 'akeegan2k@diigo.com',
  addr: {
    city: 'Juazeiro do Norte',
    street: 'Hooker',
    houseNumber: '05',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Pascal',
  lastName: 'Dankersley',
  email: 'pdankersley2l@odnoklassniki.ru',
  addr: {
    city: 'Chita',
    street: 'Myrtle',
    houseNumber: '48',
  },
  password: 'test',
  active: false,
  role: 'editor',
}, {
  firstName: 'Lothario',
  lastName: 'Gierke',
  email: 'lgierke2m@pcworld.com',
  addr: {
    city: 'Reitoca',
    street: 'Jenifer',
    houseNumber: '81',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Elwyn',
  lastName: 'Shelton',
  email: 'eshelton2n@walmart.com',
  addr: {
    city: 'Fāraskūr',
    street: 'Kenwood',
    houseNumber: '64',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Arte',
  lastName: 'Lomasny',
  email: 'alomasny2o@phpbb.com',
  addr: {
    city: 'Mabay',
    street: 'Fuller',
    houseNumber: '6',
  },
  password: 'test',
  active: false,
  role: 'admin',
}, {
  firstName: 'Brett',
  lastName: 'Climar',
  email: 'bclimar2p@jugem.jp',
  addr: {
    city: 'Wojciechów',
    street: 'Loeprich',
    houseNumber: '37509',
  },
  password: 'test',
  active: true,
  role: 'editor',
}, {
  firstName: 'Vlad',
  lastName: 'Thorowgood',
  email: 'vthorowgood2q@squarespace.com',
  addr: {
    city: 'Beipai',
    street: 'Becker',
    houseNumber: '89',
  },
  password: 'test',
  active: false,
  role: 'user',
}, {
  firstName: 'Tod',
  lastName: 'Frill',
  email: 'tfrill2r@ameblo.jp',
  addr: {
    city: 'Bolesławiec',
    street: 'Cody',
    houseNumber: '51',
  },
  password: 'test',
  active: false,
  role: 'editor',
}];
